import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { LangError } from './errors.js';
import { LAYOUT, within, ensureDir, writeJson } from './paths.js';
import { emptyState, saveState } from './state.js';
import { emptyRegistry, saveRegistry } from './vocabulary.js';
import { createGitAdapter } from './git.js';
import { TRACKED_PATHS } from './paths.js';

const templatesDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', '..', 'templates');

export function templateSource() {
  return path.join(templatesDir, 'opencode');
}

export function installTemplates(root) {
  const src = templateSource();
  if (!fs.existsSync(src)) throw new LangError(`templates not found at ${src}`);
  fs.cpSync(src, within(root, LAYOUT.opencodeDir), { recursive: true });
}

export function scaffoldInitialFiles(root) {
  ensureDir(within(root, LAYOUT.learnerDir));
  ensureDir(within(root, LAYOUT.vocabularyDir));
  ensureDir(within(root, LAYOUT.ankiDir));
  ensureDir(within(root, LAYOUT.phasesDir));
  saveState(root, emptyState());
  saveRegistry(root, emptyRegistry());
  if (!fs.existsSync(within(root, LAYOUT.planMd))) {
    fs.writeFileSync(within(root, LAYOUT.planMd), initialPlanMd(), 'utf8');
  }
  if (!fs.existsSync(within(root, LAYOUT.readmeMd))) {
    fs.writeFileSync(within(root, LAYOUT.readmeMd), learnerReadme(), 'utf8');
  }
}

function initialPlanMd() {
  return [
    '# Learning Plan',
    '',
    '> This plan is generated by the agent during `/lang-start`. It lists phases,',
    '> milestones, objectives, estimated effort, dependencies and exit criteria.',
    '> Until then, run `/lang-start` in OpenCode to set up your learner profile.',
    ''
  ].join('\n');
}

function learnerReadme() {
  return [
    '# My Language Project',
    '',
    'This project is managed by [Lang](https://github.com/), an OpenCode-native',
    'adaptive language learning system.',
    '',
    '## Start here',
    '',
    'Open this folder in OpenCode and run:',
    '',
    '```text',
    '/lang-start',
    '```',
    '',
    'Then, every study day:',
    '',
    '```text',
    '/lang-go',
    '```',
    '',
    'Check progress with `/lang-status`, request review with `/lang-review`.',
    '',
    '## Layout',
    '',
    '- `learner/` — your profile and progress state',
    '- `phases/` — curriculum phases, plans, tests, session logs',
    '- `vocabulary/` — vocabulary registry and Anki CSV exports',
    '- `plan.md` — the overall curriculum plan',
    '',
    'Progress is committed to Git after every session, so history is never lost.',
    ''
  ].join('\n');
}

export function checkGitAvailable(git) {
  const version = git.version();
  if (!version) {
    throw new LangError(
      'git is required but was not found on PATH.\n' +
      'install it first:\n' +
      '  windows: winget install --id Git.Git  (or https://git-scm.com/downloads)\n' +
      '  macos:   brew install git\n' +
      '  linux:   sudo apt install git   |   sudo dnf install git\n' +
      'then re-run "lang init --here". nothing was modified.'
    );
  }
  return version;
}

export function checkEmptyDir(root) {
  const entries = fs.readdirSync(root);
  if (entries.length > 0) {
    throw new LangError(
      `directory is not empty (found ${entries.length} entr${entries.length === 1 ? 'y' : 'ies'}). ` +
      '"lang init --here" expects an empty, new project folder. nothing was modified.'
    );
  }
}

export function checkNotNestedRepo(root, git) {
  const top = git.repoTopLevel();
  if (top) {
    throw new LangError(
      `this directory is inside an existing git repository (${top}). ` +
      'lang does not create nested repositories. run "lang init --here" in a fresh folder outside any repo. nothing was modified.'
    );
  }
}

export function initProject(root, { gitBin } = {}) {
  const git = createGitAdapter(root, { gitBin });
  checkGitAvailable(git);
  checkEmptyDir(root);
  checkNotNestedRepo(root, git);

  scaffoldInitialFiles(root);
  installTemplates(root);

  git.init();
  git.setLocalIdentityIfMissing('Lang Learner', 'learner@lang.local');
  git.add(TRACKED_PATHS);
  git.commit('chore(init): initialize lang project');
  return { root, branch: git.currentBranch() };
}
